[package]
name = "sandbox-program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
solana-program = "2.0"

[dev-dependencies]
mollusk-svm = "0.0.3"
solana-sdk = "2.0"
